[workspace]
name = "rgmin"
channels = ["conda-forge"]
platforms = ["linux-64"]

[environments]
docs = { features = ["docs"] }

[feature.docs]
platforms = ["linux-64"]

[feature.docs.dependencies]
doxygen = ">=1.13.2,<2"
sphinx = ">=8.0,<8.1"
emacs = ">=30.2,<31"
pandoc = ">=3.1,<4"

[feature.docs.pypi-dependencies]
sphinx-sitemap = ">=2.9.0, <3"
shibuya = ">=2026.1.9, <2027"
myst-parser = ">=4.0, <5"
sphinxcontrib-bibtex = ">=2.6, <3"

[feature.docs.tasks]
docs-export = { cmd = "emacs --batch -l export.el", cwd = "docs" }
docs-build = { cmd = "sphinx-build -b html -n docs/source docs/build", depends-on = ["docs-export"] }

[tasks]
