#ifndef XTS_OPTIMIZE_H
#define XTS_OPTIMIZE_H

/*
 * Compatibility skin. The C ABI is include/rgmin.h.
 * Every xts_* name here is an alias of the rgmin_* symbol.
 * New C and C++ should include rgmin.h / rgmin/optimize.hpp.
 */
#include "rgmin.h"

#define XTS_SUCCESS RGMIN_SUCCESS
#define XTS_INVALID_PARAMETER RGMIN_INVALID_PARAMETER
#define XTS_INTERNAL_ERROR RGMIN_INTERNAL_ERROR
#define XTS_UNSUPPORTED_DEVICE RGMIN_UNSUPPORTED_DEVICE
#define XTS_UNAVAILABLE RGMIN_UNAVAILABLE

#define XTS_ABI_VERSION_MAJOR RGMIN_ABI_VERSION_MAJOR
#define XTS_ABI_VERSION_MINOR RGMIN_ABI_VERSION_MINOR
#define XTS_ABI_LAYOUT_REVISION RGMIN_ABI_LAYOUT_REVISION

typedef rgmin_status_t xts_status_t;
typedef rgmin_abi_stamp_t xts_abi_stamp_t;
typedef rgmin_method_t xts_method_t;
typedef rgmin_conjugacy_t xts_conjugacy_t;
typedef rgmin_control_t xts_control_t;
typedef rgmin_report_t xts_report_t;
typedef rgmin_eval_fn xts_eval_fn;
typedef rgmin_grad_fn xts_grad_fn;
typedef rgmin_hess_fn xts_hess_fn;
typedef rgmin_evalgrad_fn xts_evalgrad_fn;
typedef rgmin_solver_t xts_solver_t;
typedef rgmin_qn_step_t xts_qn_step_t;
typedef rgmin_accept_t xts_accept_t;
typedef rgmin_manifold_t xts_manifold_t;
typedef rgmin_curv_fn xts_curv_fn;
typedef rgmin_scg_params_t xts_scg_params_t;
typedef rgmin_eigen_kind_t xts_eigen_kind_t;
typedef rgmin_eigen_params_t xts_eigen_params_t;
typedef rgmin_lowest_mode_t xts_lowest_mode_t;
typedef rgmin_hvp_fn xts_hvp_fn;

#define XTS_POLAK_RIBIERE RGMIN_POLAK_RIBIERE
#define XTS_FLETCHER_REEVES RGMIN_FLETCHER_REEVES
#define XTS_BFGS RGMIN_BFGS
#define XTS_LBFGS RGMIN_LBFGS
#define XTS_SR1 RGMIN_SR1
#define XTS_ADAM RGMIN_ADAM
#define XTS_STEEPEST RGMIN_STEEPEST
#define XTS_SR2 RGMIN_SR2
#define XTS_PSO RGMIN_PSO
#define XTS_HESTENES_STIEFEL RGMIN_HESTENES_STIEFEL
#define XTS_DAI_YUAN RGMIN_DAI_YUAN
#define XTS_CONJUGATE_DESCENT RGMIN_CONJUGATE_DESCENT
#define XTS_HAGER_ZHANG RGMIN_HAGER_ZHANG
#define XTS_LIU_STOREY RGMIN_LIU_STOREY
#define XTS_FR_PR RGMIN_FR_PR
#define XTS_NEWTON RGMIN_NEWTON
#define XTS_RFO RGMIN_RFO
#define XTS_FIRE RGMIN_FIRE
#define XTS_BB RGMIN_BB
#define XTS_DOGLEG RGMIN_DOGLEG
#define XTS_FIRE2 RGMIN_FIRE2

#define XTS_CONJUGACY_FLETCHER_REEVES RGMIN_CONJUGACY_FLETCHER_REEVES
#define XTS_CONJUGACY_POLAK_RIBIERE RGMIN_CONJUGACY_POLAK_RIBIERE
#define XTS_CONJUGACY_HESTENES_STIEFEL RGMIN_CONJUGACY_HESTENES_STIEFEL
#define XTS_CONJUGACY_DAI_YUAN RGMIN_CONJUGACY_DAI_YUAN
#define XTS_CONJUGACY_CONJUGATE_DESCENT RGMIN_CONJUGACY_CONJUGATE_DESCENT
#define XTS_CONJUGACY_HAGER_ZHANG RGMIN_CONJUGACY_HAGER_ZHANG
#define XTS_CONJUGACY_LIU_STOREY RGMIN_CONJUGACY_LIU_STOREY
#define XTS_CONJUGACY_FR_PR RGMIN_CONJUGACY_FR_PR

#define XTS_QN_LBFGS RGMIN_QN_LBFGS
#define XTS_QN_NEWTON RGMIN_QN_NEWTON
#define XTS_QN_RFO RGMIN_QN_RFO

#define XTS_ACCEPT_NONE RGMIN_ACCEPT_NONE
#define XTS_ACCEPT_ENERGY RGMIN_ACCEPT_ENERGY
#define XTS_ACCEPT_NONMONOTONE RGMIN_ACCEPT_NONMONOTONE

#define xts_version rgmin_version
#define xts_abi_stamp rgmin_abi_stamp
#define xts_abi_compatible rgmin_abi_compatible
#define xts_last_error rgmin_last_error
#define xts_tensor_borrow_cpu_f64 rgmin_tensor_borrow_cpu_f64
#define xts_tensor_free rgmin_tensor_free
#define xts_minimize rgmin_minimize
#define xts_minimize_hess rgmin_minimize_hess
#define xts_minimize_eindir rgmin_minimize_eindir
#define xts_minimize_scg rgmin_minimize_scg
#define xts_solver_create rgmin_solver_create
#define xts_solver_free rgmin_solver_free
#define xts_solver_forget rgmin_solver_forget
#define xts_solver_rebase rgmin_solver_rebase
#define xts_solver_set_maxmove rgmin_solver_set_maxmove
#define xts_solver_set_qn_step rgmin_solver_set_qn_step
#define xts_solver_set_accept rgmin_solver_set_accept
#define xts_solver_push_pair rgmin_solver_push_pair
#define xts_solver_search_direction rgmin_solver_search_direction
#define xts_solver_set_atom_maxmove rgmin_solver_set_atom_maxmove
#define xts_solver_set_project_rigid rgmin_solver_set_project_rigid
#define xts_solver_set_extra_updates rgmin_solver_set_extra_updates
#define xts_solver_set_cautious rgmin_solver_set_cautious
#define xts_solver_set_highs rgmin_solver_set_highs
#define xts_solver_set_box rgmin_solver_set_box
#define xts_solver_set_trust rgmin_solver_set_trust
#define xts_solver_add_equality rgmin_solver_add_equality
#define xts_solver_clear_equalities rgmin_solver_clear_equalities
#define xts_solver_set_highs_solver rgmin_solver_set_highs_solver
#define xts_solver_set_highs_crossover rgmin_solver_set_highs_crossover
#define xts_solver_set_highs_callback rgmin_solver_set_highs_callback
#define XTS_HIGHS_CHOOSE RGMIN_HIGHS_CHOOSE
#define XTS_HIGHS_SIMPLEX RGMIN_HIGHS_SIMPLEX
#define XTS_HIGHS_IPM RGMIN_HIGHS_IPM
#define XTS_HIGHS_IPX RGMIN_HIGHS_IPX
#define XTS_HIGHS_HIPO RGMIN_HIGHS_HIPO
#define XTS_HIGHS_PDLP RGMIN_HIGHS_PDLP
#define XTS_HIGHS_HIPDLP RGMIN_HIGHS_HIPDLP
#define XTS_HIGHS_QPASM RGMIN_HIGHS_QPASM
#define XTS_HIGHS_CROSSOVER_CHOOSE RGMIN_HIGHS_CROSSOVER_CHOOSE
#define XTS_HIGHS_CROSSOVER_ON RGMIN_HIGHS_CROSSOVER_ON
#define XTS_HIGHS_CROSSOVER_OFF RGMIN_HIGHS_CROSSOVER_OFF
#define xts_solver_set_manifold rgmin_solver_set_manifold
#define xts_solver_set_oblique rgmin_solver_set_oblique
#define xts_solver_set_stiefel rgmin_solver_set_stiefel
#define xts_solver_set_complex_circle rgmin_solver_set_complex_circle
#define xts_solver_set_euclidean_complex rgmin_solver_set_euclidean_complex
#define xts_solver_set_constant rgmin_solver_set_constant
#define xts_solver_set_multinomial_ds rgmin_solver_set_multinomial_ds
#define xts_solver_set_multinomial_sym rgmin_solver_set_multinomial_sym
#define xts_solver_set_sphere_complex rgmin_solver_set_sphere_complex
#define xts_solver_set_positive rgmin_solver_set_positive
#define xts_solver_set_centered_matrix rgmin_solver_set_centered_matrix
#define xts_solver_set_masses rgmin_solver_set_masses
#define xts_solver_set_periodic rgmin_solver_set_periodic
#define xts_solver_step rgmin_solver_step
#define xts_solver_step_hess rgmin_solver_step_hess
#define xts_solver_step_fg rgmin_solver_step_fg
#define xts_solver_step_hess_fg rgmin_solver_step_hess_fg
#define xts_lowest_eigenpair rgmin_lowest_eigenpair

#define XTS_EIGEN_LANCZOS RGMIN_EIGEN_LANCZOS
#define XTS_EIGEN_RAYLEIGH_RITZ RGMIN_EIGEN_RAYLEIGH_RITZ
#define XTS_EIGEN_JACOBI_DAVIDSON RGMIN_EIGEN_JACOBI_DAVIDSON
#define XTS_EIGEN_LOBPCG RGMIN_EIGEN_LOBPCG
#define XTS_EIGEN_PRIMME RGMIN_EIGEN_PRIMME
#define XTS_EIGEN_SLEPC RGMIN_EIGEN_SLEPC
#define XTS_EIGEN_CHASE RGMIN_EIGEN_CHASE
#define XTS_EIGEN_ELPA RGMIN_EIGEN_ELPA
#define XTS_EIGEN_ELPA2 RGMIN_EIGEN_ELPA2
#define XTS_EIGEN_SLATE RGMIN_EIGEN_SLATE
#define XTS_EIGEN_MAGMA RGMIN_EIGEN_MAGMA
#define XTS_EIGEN_CUSOLVER RGMIN_EIGEN_CUSOLVER
#define XTS_EIGEN_DLA_FUTURE RGMIN_EIGEN_DLA_FUTURE
#define XTS_EIGEN_EIGENEXA RGMIN_EIGEN_EIGENEXA
#define XTS_EIGEN_DIMER RGMIN_EIGEN_DIMER

#define XTS_MANIFOLD_EUCLIDEAN RGMIN_MANIFOLD_EUCLIDEAN
#define XTS_MANIFOLD_SPHERE RGMIN_MANIFOLD_SPHERE
#define XTS_MANIFOLD_SO3 RGMIN_MANIFOLD_SO3
#define XTS_MANIFOLD_STIEFEL RGMIN_MANIFOLD_STIEFEL
#define XTS_MANIFOLD_SE3 RGMIN_MANIFOLD_SE3
#define XTS_MANIFOLD_RIGID_QUOTIENT RGMIN_MANIFOLD_RIGID_QUOTIENT
#define XTS_MANIFOLD_MW_RIGID RGMIN_MANIFOLD_MW_RIGID
#define XTS_MANIFOLD_OBLIQUE RGMIN_MANIFOLD_OBLIQUE
#define XTS_MANIFOLD_MULTINOMIAL RGMIN_MANIFOLD_MULTINOMIAL
#define XTS_MANIFOLD_COMPLEX_CIRCLE RGMIN_MANIFOLD_COMPLEX_CIRCLE
#define XTS_MANIFOLD_SYMMETRIC RGMIN_MANIFOLD_SYMMETRIC
#define XTS_MANIFOLD_SKEWSYMMETRIC RGMIN_MANIFOLD_SKEWSYMMETRIC
#define XTS_MANIFOLD_EUCLIDEAN_COMPLEX RGMIN_MANIFOLD_EUCLIDEAN_COMPLEX
#define XTS_MANIFOLD_CONSTANT RGMIN_MANIFOLD_CONSTANT
#define XTS_MANIFOLD_MULTINOMIAL_DS RGMIN_MANIFOLD_MULTINOMIAL_DS
#define XTS_MANIFOLD_MULTINOMIAL_SYM RGMIN_MANIFOLD_MULTINOMIAL_SYM
#define XTS_MANIFOLD_SPHERE_COMPLEX RGMIN_MANIFOLD_SPHERE_COMPLEX
#define XTS_MANIFOLD_POSITIVE RGMIN_MANIFOLD_POSITIVE
#define XTS_MANIFOLD_CENTERED_MATRIX RGMIN_MANIFOLD_CENTERED_MATRIX

#endif /* XTS_OPTIMIZE_H */
